//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IonHeartHealthService.DataObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class TodoItems
    {
        public string Id { get; set; }
        public string Text { get; set; }
        public bool Complete { get; set; }
        public byte[] Version { get; set; }
        public System.DateTimeOffset CreatedAt { get; set; }
        public Nullable<System.DateTimeOffset> UpdatedAt { get; set; }
        public bool Deleted { get; set; }
        public Nullable<System.DateTime> CalendarDate { get; set; }
        public string Heartrate { get; set; }
        public string HeartrateComment { get; set; }
        public string Weight { get; set; }
        public string WeightComment { get; set; }
        public string Length { get; set; }
        public string LengthComment { get; set; }
        public string WellBeing { get; set; }
        public string WellBeingComment { get; set; }
        public string Notes { get; set; }
        public string BreathFrequency { get; set; }
        public string BreathFrequencyComment { get; set; }
        public string EKG { get; set; }
        public string FluidBody { get; set; }
        public string FluidLungs { get; set; }
        public string BloodPressure { get; set; }
        public string BloodOxygen { get; set; }
    }
}
